### ISSUE TITLE
WPS support plans and references

### ISSUE THREAD

**Issue by Zduniusz** [libwifi/libwifi#19]
Hi,

In my project, I'm looking for a way to create WPS packets and parse responses. Are there any plans for implementation?

I understand that this is a very complex task that involves at least:
 - Implementation of 802.11X (EAP)
 - Implementation of WPS on top of the EAP protocol
 
For the time being, I'm probably just going to use raw packets captured from Wireshark and `memcpy` specific parameters such as MACs, etc.

I would be very grateful if you could provide references for resources that you have used in creating this project and these illustrations:

https://github.com/libwifi/libwifi/blob/0a36a1816bd461f7c12867989918435f097895ad/src/libwifi/core/frame/management/assoc_request.h#L23-L38

**Comment by foxtrot** [comment]
The library has data frame support, which is in my opinion the best way to keep complexity of the library down instead of adding extra structs and features around specific data frame content, such as EAP for example.

The design goal is for the library user to be able to build out any data they'd want to send and then be able to simply point to it with a libwifi_data struct.

**Comment by foxtrot** [comment]
I'd recommend defining your data packets/frames as a C struct that you can simply malloc and reference with libwifi, instead of hand patching and re-broadcasting captured frames.
