### ISSUE TITLE
About how to reference this library to run through the WiFi protocol

### ISSUE THREAD

**Issue by CAIJUN111** [libwifi/libwifi#21]
Hi, I read your project, I think it is great, but why not give an example of how to run the whole working steps of WiFi?

There is also a question about many source files referring to the header file pcap.h, I can not find it throughout the project ,is  this project islacking the necessary other source files?

 Looking forward to your reply.

**Comment by CAIJUN111** [comment]
> Hi, I read your project, I think it is great, but why not give an example of how to run the whole working steps of WiFi?
> 
> There is also a question about many source files referring to the header file pcap.h, I can not find it throughout the project ,is this project islacking the necessary other source files?
> 
> Looking forward to your reply.

Add that my project is based on esp32 and I find that I may need to port the pcap library.

**Comment by foxtrot** [comment]
Hi,

Only the examples should contain pcap.h (libpcap) references, since libpcap is used to open a handle on the interface or file for writing/reading packets. I'll update the README to mention this.

>Add that my project is based on esp32 and I find that I may need to port the pcap library.
This is outside of the scope for this project, but I'd find it hard to believe if nobody else has put libpcap on an ESP32.
